apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rag7-sep12-1
  janus-idp.io/tekton: rag7-sep12-1
  backstage.io/kubernetes-id: rag7-sep12-1
  backstage.io/kubernetes-namespace: rag7-sep12-1 
  app.kubernetes.io/part-of: rag7-sep12-1
resources: 
- initialize-namespace.yaml
- pvc.yaml
- deployment-model-server.yaml
- service-model-server.yaml
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml
- deployment-database.yaml
- service-database.yaml
- database-config.yaml
- rhoai/
